theme = "showfolio"
languageCode = "en-us"
baseurl = "/"
title = "Home"

[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "Tugi Gantulga"
  authorEmail = "gantulga01@allegheny.com"
  authorImage = "/photo.jpeg"
  autoDarkMode = false

  copyright = "Copyright © 2021 - Tugi Gantulga · All rights reserved"
  favicon = "star.ico"

[params.homepage]
  title = "Hey 👋 I'm Tugi!"
  tagline = "Full Stack Developer"
  description = "A student who develops functional websites to provide valuable experience to customers."
  contact = "https://www.linkedin.com/in/tugi/"

[params.homepage.codepen]
  username = "tuduun"
  pens = ["SmartContractColorchanger", "CryptoTokens", "LiveChatBox", "PoWBlockchain", "SimonGame"]

[params.homepage.resume]
  skills = ["Smart Contracts", "Web Development"]

[[params.homepage.resume.work]]
  name = "URECA"
  role = "Software & Blockchain intern"
  duration = "Jun 2022 - Sep 2022"
[[params.homepage.resume.work]]
  name = "Pelletier Library"
  role = "Front Desk"
  duration = "Sep 2022 - Present"

[[params.homepage.resume.courses]]
  name = "Web Development"
  provider = "Allegheny College"
  duration = "Feb 2022 - May 2022"

[[params.homepage.resume.courses]]
  name = "Computer Organization"
  provider = "Allegheny College"
  duration = "Aug 2022 - Dec 2022"

[params.homepage.social]
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/tugi"
  github = "https://github.com/tuduun"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
